######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 27 14:19:19 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .  /usr/include 
LIBS = -L/usr/local/lib -lzim -lcxxtools
; CONFIG = warn_on

# Input
SOURCES += main.cpp htmlarea.cpp qmain.cpp
HEADERS += htmlarea.h qmain.h